export const initForm = {
  name: '',
  video_url: '',
  campus_id: 1,
  teacher_id: 1,
  subject_id: 3,
  semester_id: 1,
  product_type_id: '',
  class: 'pt12365',
  image_url: '',
  resource_url: '',
  students: [],
  galleries: [],
  description: '',
  status: 0,
};
